# Resolve react_native_pods.rb with node (works with hoisted node_modules)
require Pod::Executable.execute_command(
  'node',
  ['-p', 'require.resolve("react-native/scripts/react_native_pods.rb", {paths: [process.argv[1]]})', __dir__]
).strip

# Expo autolinking for bare workflow
expo_autolinking_script = Pod::Executable.execute_command(
  'node',
  ['-p', 'require.resolve("expo/package.json", {paths: [process.argv[1], process.cwd(), process.cwd() + "/.."]})', __dir__]
).strip
require File.join(File.dirname(expo_autolinking_script), 'scripts/autolinking')

$RNFirebaseAsStaticFramework = true
ENV['RCT_NEW_ARCH_ENABLED'] = '0'

platform :ios, '15.1'
prepare_react_native_project!

target 'faleyna' do
  use_expo_modules!

  config = use_native_modules!
  use_frameworks! linkage: :static

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    rn_root = File.expand_path(config[:reactNativePath], Pod::Config.instance.installation_root)
    react_common = File.join(rn_root, 'ReactCommon')

    universal_headers = [
      '$(inherited)',
      '$(PODS_ROOT)/Headers/Public',
      '$(PODS_ROOT)/Headers/Private',
      '"${PODS_CONFIGURATION_BUILD_DIR}/**"',
      '$(PODS_ROOT)/React-Core/React',
      '$(PODS_ROOT)/React-Core/React/Fabric',
      '$(PODS_ROOT)/React-Core/React/Fabric/Mounting',
      "\"#{react_common}\"",
      "\"#{File.join(react_common, 'runtimeexecutor')}\"",
      "\"#{File.join(react_common, 'runtimeexecutor', 'ReactCommon')}\"",
      '"${PODS_CONFIGURATION_BUILD_DIR}/ReactCommon/ReactCommon.framework/Headers"'
    ].join(' ')

    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |cfg|
        cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        cfg.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        cfg.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        cfg.build_settings['HEADER_SEARCH_PATHS'] = "#{universal_headers} $(inherited)"
        cfg.build_settings['OTHER_CFLAGS'] = [
          cfg.build_settings['OTHER_CFLAGS'] || '$(inherited)',
          '-isystem $(PODS_ROOT)/RCT-Folly',
          '-isystem $(PODS_ROOT)/boost',
          '-isystem $(PODS_ROOT)/DoubleConversion',
          '-isystem $(PODS_ROOT)/fmt/include',
          "-isystem \"#{react_common}\"",
          "-isystem \"#{File.join(react_common, 'runtimeexecutor')}\"",
          "-isystem \"#{File.join(react_common, 'runtimeexecutor', 'ReactCommon')}\""
        ].join(' ')
      end
    end
  end
end
